baseURL = 'https://blog.hoss-movies.com/'
languageCode = 'en-us'
title = "Caleb's Personal Writings"
theme = 'mana'

[params]
darkMode = true
favicon = "/images/favicon.png"
description = "A collection of some of my creative writings past and present."
sectionTitle = "Writings"

[[menu.main]]
  name = "Stories"
  url = "/stories/"
  weight = 1

[[menu.main]]
  name = "Poetry"
  url = "/poetry/"
  weight = 2

[[menu.main]]
  name = "Miscellaneous"
  url = "/misc/"
  weight = 3

[taxonomies]
  tag = "tags"
  category = "categories"

[params.avatar]
  [params.avatar.home]
    assetPath = "/images/favicon.png"
  [params.avatar.about]
    assetPath = "/images/favicon.png"