site_name: Caleb's Personal Writings
site_url: https://blog.hoss-movies.com/
nav:
  - Home: index.md
  - Stories:
      - Stories: stories/index.md
      - The Cliff: stories/the-cliff.md
  - Poetry:
      - Poetry: poetry/index.md
      - the Tide: poetry/the-tide.md
  - Miscellaneous:
      - Miscellaneous: misc/index.md
      - Love: misc/love.md
theme: 
  name: material
  favicon: images/favicon.png
  logo: images/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode